// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmTn0wTB5tg6X-eb3FYunqOx37X_xnvLk',
    appId: '1:279983312401:web:8ec1422fb2b8e5c4eeabb0',
    messagingSenderId: '279983312401',
    projectId: 'task-time-tracker-flutter',
    authDomain: 'task-time-tracker-flutter.firebaseapp.com',
    storageBucket: 'task-time-tracker-flutter.appspot.com',
    measurementId: 'G-GHWJ4E5FSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ONpS3srIMPju2kiUDLdZmxP8foWb7OU',
    appId: '1:279983312401:android:7de86c8547d15895eeabb0',
    messagingSenderId: '279983312401',
    projectId: 'task-time-tracker-flutter',
    storageBucket: 'task-time-tracker-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7pzoFo3pHPTEkiYrpo5JQsQtT9UY5_KI',
    appId: '1:279983312401:ios:725ae8d5bb90249deeabb0',
    messagingSenderId: '279983312401',
    projectId: 'task-time-tracker-flutter',
    storageBucket: 'task-time-tracker-flutter.appspot.com',
    iosClientId:
        '279983312401-vu280eo3i8n9i1hqhldcgt6a1vrif0vd.apps.googleusercontent.com',
    iosBundleId: 'com.taskTimeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7pzoFo3pHPTEkiYrpo5JQsQtT9UY5_KI',
    appId: '1:279983312401:ios:725ae8d5bb90249deeabb0',
    messagingSenderId: '279983312401',
    projectId: 'task-time-tracker-flutter',
    storageBucket: 'task-time-tracker-flutter.appspot.com',
    iosClientId:
        '279983312401-vu280eo3i8n9i1hqhldcgt6a1vrif0vd.apps.googleusercontent.com',
    iosBundleId: 'com.taskTimeTracker',
  );
}
